language: go
go:
- 1.5
env: PATH=/home/travis/gopath/bin:$PATH
install:
- go get github.com/laher/goxc
- sudo apt-get update
- DEBIAN_FRONTEND=noninteractive sudo apt-get install -y rpm devscripts debhelper
- mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
script:
- make all
after_script:
- make cover
after_success:
- script/travis/autotag.sh
before_deploy:
- make rpm deb
deploy:
  provider: releases
  api_key:
    secure: Rzt3UJJnYi51r53yVpvg+5McqPEV+qLig6VPW+2V9hrSzd+25bJtoOesuWdKneHeeEkTivTzH3SillWdEDFlQdr+HBh/Th3n0M9GHKYMtI+b9z5BeqZWqJ8lSCICdTRmOwarUWSIV33JwgQ3og/bxVEGTRmqMpYMrPHWSBWGGeQ=
  file:
    - "/home/travis/rpmbuild/RPMS/noarch/mkr-0.8.0-1.noarch.rpm"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/packaging/mkr_0.8.0-1_all.deb"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_linux_amd64"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_linux_386"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_darwin_amd64"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_darwin_386"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_linux_amd64.tar.gz"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_linux_386.tar.gz"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_darwin_amd64.zip"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_darwin_386.zip"
  skip_cleanup: true
  on:
    repo: mackerelio/mkr
    tags: true
    all_branches: true
