language: go
go:
- 1.3
env: PATH=/home/travis/gopath/bin:$PATH
install:
- go get github.com/laher/goxc
- sudo apt-get update
- DEBIAN_FRONTEND=noninteractive sudo apt-get install -y rpm devscripts debhelper
- mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
script:
- goxc -t
- make all
after_success:
- script/travis/autotag.sh
before_deploy:
- make rpm deb
deploy:
  provider: releases
  api_key:
    secure: K7cIFoRCn4DrmSysTtyul14WJdY858y6MQM5hzTcIZrQnCXZZUVaBoNt7U7IiS/5rj41hiDT4635SiSxl/BIgahsUVVgzL7VRieMb5DRzjiWc8VfqmYlLwkGudaUt2FidlbuRuAHJF2PpdOTrMELJnTq4/Pva2/LkObrTAG2uok=
  file:
    - "/home/travis/rpmbuild/RPMS/noarch/mkr-0.6.0-1.noarch.rpm"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/packaging/mkr_0.6.0-1_all.deb"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_linux_amd64"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_linux_386"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_darwin_amd64"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_darwin_386"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_linux_amd64.tar.gz"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_linux_386.tar.gz"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_darwin_amd64.zip"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_darwin_386.zip"
  skip_cleanup: true
  on:
    repo: mackerelio/mkr
    tags: true
    all_branches: true
