sudo: false
language: go
go:
- 1.3
env: PATH=/home/travis/gopath/bin:$PATH
install:
- go get github.com/laher/goxc
script:
- goxc -t
- make all
deploy:
  provider: releases
  api_key:
    secure: SWuGqVWhJqHKoO6JYDdDm1UwjCBjE5CfXCnkHdogm/aTSjG2IbJGBpkbPCs1h1q6PFXAli2jmftqRzYRhTBPEWgh47smGpd2FfZczN5KIxwfZFRdgBpLo3xngmmkazlOi6MAFQGjY1zSWOznCmEEezO3wlWZNYnVkfKnxgpuSIs=
  file:
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_linux_amd64"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_linux_386"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_darwin_amd64"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_darwin_386"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_windows_amd64.exe"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_windows_386.exe"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_linux_amd64.tar.gz"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_linux_386.tar.gz"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_darwin_amd64.zip"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_darwin_386.zip"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_windows_amd64.zip"
    - "/home/travis/gopath/src/github.com/mackerelio/mkr/snapshot/mkr_windows_386.zip"
  skip_cleanup: true
  on:
    repo: mackerelio/mkr
    tags: true
    all_branches: true
