language: go
go:
- 1.6.2
env:
  global:
  - PATH=~/bin:~/gopath/bin:$PATH
  - secure: "jHn0J9ELpBEK7pLhJDNVZa8SWD2LSx4Spxm1bVu1yZzrVwOSUuNU9iJ25/RkPN+0+KK53K5rwIisXtWGU4AM49vx7CA3kMMbqJd6X4DfzT0ZEK8dZiQX6m/YbZfVQSOPsMOYQryoH4q0hPru5UR6oDhxsyxBBerL/LzPczI+AS4="
install:
- go get github.com/laher/goxc
- sudo apt-get update
- DEBIAN_FRONTEND=noninteractive sudo apt-get install -y rpm devscripts debhelper
- mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
script:
- make all
after_script:
- make cover
before_deploy:
- go get github.com/aktau/github-release
- mkdir -p ~/bin
- git clone https://github.com/github/hub.git && cd hub && script/build -o ~/bin/hub
  && cd ..
- echo $TRAVIS_BRANCH
- git config --add remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
- git fetch
- git checkout master || git checkout -b master origin/master
- git checkout $TRAVIS_BRANCH
- git fetch --depth=1000
- git fetch --tags --depth=1000 || true
- make check_variables
- make rpm deb
deploy:
- provider: script
  script: script/releng --task=upload-to-github-release -v
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: script/releng --task=create-pullrequest --current-branch=$TRAVIS_BRANCH
    -v
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^bump-version-.*$"
notifications:
  slack:
    secure: MegndYQrf9ubVA015qCORCIYows50jYmAUKNNPXZOlWRkzhIir2XVzK6m2vgZPxKmQpwcg0n1tAddmxw2lHwTC+V31UNTHaItNYo5RjRkRSC6Js1FlGeKHb/ccu0GeDy8mPo4OAiFxvQe3qY889qQ3k5Ke22fE7PGZMpC5+4/CA=
